Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Runtime.InteropServices;

namespace BaiTap_phan3.Models
{

    public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        [MaxLength(30, ErrorMessage = "Chiều dài tên không vượt quá 30 kí tự")]
        [MinLength(2, ErrorMessage = "Chiều dài tên không nhỏ hơn 3 kí tự")]
        [Required(ErrorMessage = "Tên là yêu cầu")]
        [Display(Name = "Tên")]
        public string? FirstName { get; set; }
        [MaxLength(30, ErrorMessage = "Chiều dài tên đệm không vượt quá 30 kí tự")]
        [MinLength(2, ErrorMessage = "Chiều dài tên đệm không nhỏ hơn 3 kí tự")]
        [Display(Name = "Họ")]
        [Required(ErrorMessage = "Tên đệm là yêu cầu")]
        public string? LastName { get; set; }
        [MaxLength(30, ErrorMessage = "Chiều dài tên tài khoản không vượt quá 30 kí tự")]
        [MinLength(3, ErrorMessage = "Chiều dài tên tài khoản không nhỏ hơn 3 kí tự")]
        [Required(ErrorMessage = "Tên tài khoản là yêu cầu")]
        [Display(Name = "Tên tài khoản")]
        public string? AccountName { get; set; }
        [Display(Name = "Ngày tạo")]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Trạng thái")]
        public bool IsActive { get; set; } = false;
        [MaxLength(40, ErrorMessage = "Mật khẩu tối đa 40 kí tự")]
        [MinLength(3, ErrorMessage = "Mật khẩu tối thiểu 3 kí tự")]
        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu là yêu cầu")]
        public string? PassWord { get; set; }
        [NotMapped]
        [Compare("PassWord", ErrorMessage = "Mật khẩu không trùng khớp")]
        [Display(Name = "Mật khẩu xác nhận")]
        public string? ConfirmPassWord { get; set; }
        [NotMapped]
        public virtual IEnumerable<Message>? Messages { get; set; }
        [NotMapped]
        public virtual IEnumerable<MessageRecipient>? MessRecis { get; set; }

        public string FullName()
        {
            return LastName + FirstName;
        }
    }
}

Controllers/StaffController.cs
using Microsoft.AspNetCore.Mvc;
using BaiTap_phan3.Models;
using BaiTap_phan3.Contracts.Repositories;
using OfficeOpenXml;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Drawing.Printing;
using BaiTap_phan3.Filters;


namespace BaiTap_phan3.Controllers
{
    // kiem tra trung V
    // phongban minvalue V

    // tim kiem co su uu tien V
    // select khong select all (*) V
    // them sua tra ve (id,truefalse) V

    // thêm nút bỏ lọc và áp dụng lọc V

    // sửa trả về lỗi modelstate.isvalue V
    // tìm kiếm phân trang phía db, sử dụng index và fulltext V
    [MyActionFilter]
    public class StaffController : Controller
    {
        private readonly IStaffRepository<NhanVien> _repositoryNhanVien;
        private readonly IGenericRepository<PhongBan> _repositoryPhongBan;
        private readonly IGenericRepository<ChucVu> _repositoryChucVu;
        private readonly IHostEnvironment _hostEnvironment;
        private static List<PhongBan> _phongBanList;
        private readonly List<ChucVu> _chucVuList;
        public StaffController(IHostEnvironment hostingEnvironment, IStaffRepository<NhanVien> repositoryNhanVien, IGenericRepository<PhongBan> repositoryPhongBan, IGenericRepository<ChucVu> repositoryChucVu)
        {
            _repositoryNhanVien = repositoryNhanVien;
            _repositoryPhongBan = repositoryPhongBan;
            _repositoryChucVu = repositoryChucVu;
            _hostEnvironment = hostingEnvironment;
            _phongBanList = repositoryPhongBan.GetAll().Result;
            _chucVuList = repositoryChucVu.GetAll().Result;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                PageResult<NhanVien> pageResult = await _repositoryNhanVien.TimKiem("", -1, -1, new Pagination { PageNumber = 1, PageSize = 10 });
                ViewBag.PageResult = pageResult;
                ViewBag.PhongBans = await _repositoryPhongBan.GetAll();
                ViewBag.ChucVus = await _repositoryChucVu.GetAll();
                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new ResponseError { Message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(NhanVien nhanVien)
        {
            if (nhanVien.PhongBanId == 0)
            {
                ModelState.AddModelError("PhongBanId", "PHòng ban là bắt buộc");
            }
            if (!ModelState.IsValid)
            {
                ViewBag.PhongBans = _phongBanList;
                ViewBag.ChucVus = _chucVuList;
                return Json(new ResponseError()
                {
                    Status = "Bad request",
                    Code = 400,
                    Data = RenderRazorViewToString(this, "_createStaffModal", nhanVien)
                });
            }

            if (await _repositoryNhanVien.KiemTraTrung(nhanVien))
            {
                ModelState.AddModelError("HoVaTen", "Nhân viên đã tồn tại");
                ModelState.AddModelError("NgaySinh", "Ngày sinh bị trùng");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.PhongBans = _phongBanList;
                ViewBag.ChucVus = _chucVuList;
                return Json(new ResponseError()
                {
                    Status = "Bad request",
                    Code = 400,
                    Message = "Yêu cầu không thể được thực thi do lỗi xác thực dữ liệu",
                    Data = RenderRazorViewToString(this, "_createStaffModal", nhanVien)
                });
            }
            else
            {
                int nhanVienMoi_id = await _repositoryNhanVien.Insert(nhanVien);
                return Json(new ResponseError() { Data = nhanVienMoi_id });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(NhanVien nhanVien)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.PhongBans = _phongBanList;
                ViewBag.ChucVus = _chucVuList;
                return Json(new ResponseError()
                {
                    Status = "Bad request",
                    Code = 400,
                    Message = "Yêu cầu không thể được thực thi do lỗi xác thực dữ liệu",
                    Data = RenderRazorViewToString(this, "_createStaffModal", nhanVien)
                });
            }

            if (await _repositoryNhanVien.KiemTraTrung(nhanVien))
            {
                ModelState.AddModelError("HoVaTen", "Nhân viên đã tồn tại");
                ModelState.AddModelError("NgaySinh", "Ngày sinh bị trùng");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.PhongBans = _phongBanList;
                ViewBag.ChucVus = _chucVuList;
                return Json(new ResponseError()
                {
                    Status = "Bad request",
                    Code = 400,
                    Message = "Yêu cầu không thể được thực thi do lỗi xác thực dữ liệu",
                    Data = RenderRazorViewToString(this, "_createStaffModal", nhanVien)
                });

            }
            else
            {
                //nhanVien.HoVaTen = Helper.FuncHelper.NameFormat(nhanVien.HoVaTen);
                bool isSuccess = await _repositoryNhanVien.Update(nhanVien, nhanVien.Id);
                return Json(new ResponseError() { Data = isSuccess });
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            await _repositoryNhanVien.Delete(id);
            return Json(new ResponseBase() { Status = "OK", Code = 200 });
        }

        [HttpGet]
        public async Task<IActionResult> Report(string keySearch, int phongBanId, int chucVu)
        {

            IEnumerable<NhanVien>? nhanViens = _repositoryNhanVien.TimKiem(keySearch, phongBanId, chucVu, new Pagination(), false).Result.Data;
            var filePath = ToExcel(nhanViens);
            return Json(new ResponseBase { Data = filePath });
        }

        [HttpGet]
        public IActionResult Download(string filePath, string fileName)
        {
            byte[] data = System.IO.File.ReadAllBytes(filePath);
            FileContentResult fileContentResult = File(data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            return fileContentResult;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string keySearch, int phongBanId, int chucVuId, Pagination pagination)
        {
            PageResult<NhanVien> pageResult = await _repositoryNhanVien.TimKiem(keySearch, phongBanId, chucVuId, pagination);
            ViewBag.PageResult = pageResult;
            return Json(new ResponseBase { Data = RenderRazorViewToString(this, "_staffBodyTable") });
        }

        public string ToExcel(IEnumerable<NhanVien> nhanViens)
        {
            var nhanVienList = nhanViens.ToArray();
            string templateVirtualPath = "wwwroot\\Templates\\NhanVien.xlsx";
            string fullPath = Path.Combine(_hostEnvironment.ContentRootPath, templateVirtualPath);

            ExcelPackage package = new ExcelPackage(fullPath);
            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            var sheet = package.Workbook.Worksheets[0];


            if (nhanVienList.Count() > 15)
            {
                var countAddedRow = nhanVienList.Count() - 15;
                sheet.Cells[3, 1, 3, 6].CopyStyles(sheet.Cells[18, 1, 18 + countAddedRow, 6]);
            }

            for (int row = 0; row < nhanViens.Count(); row++)
            {
                sheet.Cells[row + 3, 1].Value = row + 1;
                sheet.Cells[row + 3, 2].Value = nhanVienList[row].HoVaTen;
                sheet.Cells[row + 3, 3].Value = nhanVienList[row].NgaySinh.ToString("dd-MM-yyyy");
                sheet.Cells[row + 3, 4].Value = nhanVienList[row].DienThoai;
                sheet.Cells[row + 3, 5].Value = nhanVienList[row].PhongBan.TenPhongBan;
                sheet.Cells[row + 3, 6].Value = nhanVienList[row].ChucVu;
            }

            // destination path
            string location = "wwwroot\\Templates\\NhanVienBaoCao.xlsx";
            string newFilePath = Path.Combine(_hostEnvironment.ContentRootPath, location);

            if (System.IO.File.Exists(newFilePath))
            {
                System.IO.File.Delete(newFilePath);
            }

            package.SaveAs(new FileInfo(newFilePath));
            return newFilePath;
        }

        public static string RenderRazorViewToString(Controller controller, string viewName, object model = null)
        {
            controller.ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                IViewEngine viewEngine = controller.HttpContext.RequestServices.GetService(typeof(ICompositeViewEngine)) as ICompositeViewEngine;
                ViewEngineResult viewResult = viewEngine.FindView(controller.ControllerContext, viewName, false);

                ViewContext viewContext = new ViewContext(
                    controller.ControllerContext,
                    viewResult.View,
                    controller.ViewData,
                    controller.TempData,
                    sw,
                    new HtmlHelperOptions()
                );
                viewResult.View.RenderAsync(viewContext);
                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

Controllers/UserController.cs
using MessageApp2.DATA;
using BaiTap_phan3.Models;
using Microsoft.AspNetCore.Mvc;
using BaiTap_phan3.Filters;

namespace MessageApps2.Controllers{

    [MyActionFilter]
    public class UserController: Controller{
        private readonly AppDbContext _appDbContext;
        public UserController(IConfiguration configuration)
        {

            _appDbContext = new AppDbContext(configuration);
        }

        public IActionResult Index(){
            ViewBag.Users = _appDbContext.Users;
            return View();
        }

        [HttpGet]
        public IActionResult Create(){
            return View();
        }

        [HttpPost]
        public IActionResult Create(User user){
            if(!ModelState.IsValid){
                return View(user);
            }
            string newAccountName = user.AccountName.ToLower();
            if(_appDbContext.Users.ToList().FirstOrDefault(user => user.AccountName.ToLower()==newAccountName)!=null){
                ModelState.AddModelError("AccountName","Tên tài khoản đã tồn tại");
            }
             if(!ModelState.IsValid){
                return View(user);
            }
            user.CreatedDate = DateTime.Now;
            _appDbContext.Users.Add(user);
            _appDbContext.SaveChanges();
            return RedirectToAction("Index","User");
        }
    }
}

Views/User/Create.cshtml
@model BaiTap_phan3.Models.User;

@{
    ViewData["Title"] = "User create";
}

@{
    <form style="width: 60%; background-color:rgb(169, 169, 211)" asp-action="Create" asp-controller="User" method="post" class="container">
        <div class="form-group">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" type="text"  class="form-control">
            <span class="error-holder" asp-validation-for="FirstName"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" type="text"  class="form-control">
            <span class="error-holder"  asp-validation-for="LastName"></span>
        </div>
         <div class="form-group">
            <label asp-for="AccountName"></label>
            <input asp-for="AccountName" type="text"  class="form-control">
            <span class="error-holder"  asp-validation-for="AccountName"></span>
        </div>
        <div class="form-group">
            <label asp-for="PassWord"></label>
            <input asp-for="PassWord" type="password"  class="form-control" value=""> 
            <span class="error-holder"  asp-validation-for="PassWord"></span>
        </div>
        <div class="form-group">
            <label asp-for="ConfirmPassWord"></label>
            <input asp-for="ConfirmPassWord" type="password"  class="form-control">
            <span class="error-holder"  asp-validation-for="ConfirmPassWord"></span>
        </div>

        <button class="btn btn-danger" style="color: white;" type="submit">ok</button>
    </form>
}

Views/User/Index.cshtml
@using BaiTap_phan3.Models
@using static BaiTap_phan3.Models.User
@{
    ViewData["Title"] = "User-Index";
    ViewData["log"] = "Log out";
    int index = 0;
}

@section nav {
    <li class="nav-item">
        <a id="staff-link" class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Quản lý
            nhân viên</a>
    </li>
    <li class="nav-item">
        <a id="staff-link" class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">
            User</a>
    </li>
}

@{
    <div class="Tool-container">
        <a class="btn" id="staff-link" style="background-color: rgb(210, 210, 244); border-radius:3px" class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">
            Create user</a>
    </div>
    <table class="table user-table">
        <thead>
            <tr>
                <th>STT</th>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Account Name</th>
                <th>Password</th>
                <th>Created date</th>
                <th>Is active</th>
            </tr>
        </thead>
        <tbody>
            @foreach (User user in ViewBag.Users)
            {
                index++;
                <tr>
                    <td>@index</td>
                    <td>@user.UserId</td>
                    <td>@user.FirstName</td>
                    <td>@user.LastName</td>
                    <td>@user.AccountName</td>
                    <td>@user.PassWord</td>
                    <td>@user.CreatedDate</td>
                    <td>@user.IsActive</td>
                </tr>
            }
        </tbody>
    </table>
}